In [6]:
import numpy as np
import pandas as pd

In [ ]:
print("ok")

In [7]:
arr = np.arange(5, 30, 2)
print(arr)
print(arr[arr % 3 == 0])

brr = np.array(["aaa", "bbb", "ccc"])
print(brr[brr == "bbb"])

[ 5  7  9 11 13 15 17 19 21 23 25 27 29]
[ 9 15 21 27]
['bbb']


In [10]:
ccc = np.zeros((4, 7))
print(ccc)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [13]:
ccc[1, ] = 2
ccc

array([[0., 0., 0., 0., 0., 0., 0.],
       [2., 2., 2., 2., 2., 2., 2.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])